function []=plot_box(lon,lat,x1,x2,y1,y2,color_line,lsize)

plot([lon(x1) lon(x1)],[lat(y1) lat(y2)],color_line,...
     [lon(x2) lon(x2)],[lat(y1) lat(y2)],color_line,...
     [lon(x1) lon(x2)],[lat(y1) lat(y1)],color_line,...
     [lon(x1) lon(x2)],[lat(y2) lat(y2)],color_line,'linewidth',lsize);

return
